apiVersion: v1
kind: Pod
metadata:
  labels:
    run: app1
  name: app1
  namespace: dev
spec:
  containers:
  - image: httpd
    name: app1
    ports:
      - containerPort: 80
        name: http 
        protocol: TCP
 